HTMLAnchorElement = function HTMLAnchorElement (){
    globalMy.error("Illegal constructor", `"TypeError: Illegal constructor
    at snippet:///%E8%84%9A%E6%9C%AC%E4%BB%A3%E7%A0%81%E6%AE%B5%20%2332:2:6"`);
}
globalMy.functionprotect(HTMLAnchorElement);
globalMy.rename(HTMLAnchorElement.prototype,"HTMLAnchorElement")
Object.setPrototypeOf(HTMLAnchorElement.prototype,HTMLElement.prototype);

// HTMLAnchorElement.prototype.__proto__ = HTMLElement.prototype
HTMLAnchorElement.__proto__ = HTMLElement;

globalMy.mydefineProperty(HTMLAnchorElement.prototype,'target','',true,undefined,undefined,function target(){debugger;return globalMy.value.HTMLAnchorElement_target;},function target(val){debugger;globalMy.value.HTMLAnchorElement_target=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).target.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).target.set,'set');
globalMy.value.HTMLAnchorElement_target='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'download','',true,undefined,undefined,function download(){debugger;return globalMy.value.HTMLAnchorElement_download;},function download(val){debugger;globalMy.value.HTMLAnchorElement_download=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).download.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).download.set,'set');
globalMy.value.HTMLAnchorElement_download='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'ping','',true,undefined,undefined,function ping(){debugger;return globalMy.value.HTMLAnchorElement_ping;},function ping(val){debugger;globalMy.value.HTMLAnchorElement_ping=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).ping.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).ping.set,'set');
globalMy.value.HTMLAnchorElement_ping='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'rel','',true,undefined,undefined,function rel(){debugger;return globalMy.value.HTMLAnchorElement_rel;},function rel(val){debugger;globalMy.value.HTMLAnchorElement_rel=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).rel.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).rel.set,'set');
globalMy.value.HTMLAnchorElement_rel='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'relList',{},true,undefined,undefined,function relList(){debugger;return globalMy.value.HTMLAnchorElement_relList;},function relList(val){debugger;globalMy.value.HTMLAnchorElement_relList=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).relList.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).relList.set,'set');
globalMy.value.HTMLAnchorElement_relList={};
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'hreflang','',true,undefined,undefined,function hreflang(){debugger;return globalMy.value.HTMLAnchorElement_hreflang;},function hreflang(val){debugger;globalMy.value.HTMLAnchorElement_hreflang=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hreflang.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hreflang.set,'set');
globalMy.value.HTMLAnchorElement_hreflang='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'type','',true,undefined,undefined,function type(){debugger;return globalMy.value.HTMLAnchorElement_type;},function type(val){debugger;globalMy.value.HTMLAnchorElement_type=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).type.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).type.set,'set');
globalMy.value.HTMLAnchorElement_type='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'referrerPolicy','',true,undefined,undefined,function referrerPolicy(){debugger;return globalMy.value.HTMLAnchorElement_referrerPolicy;},function referrerPolicy(val){debugger;globalMy.value.HTMLAnchorElement_referrerPolicy=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).referrerPolicy.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).referrerPolicy.set,'set');
globalMy.value.HTMLAnchorElement_referrerPolicy='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'text','',true,undefined,undefined,function text(){debugger;return globalMy.value.HTMLAnchorElement_text;},function text(val){debugger;globalMy.value.HTMLAnchorElement_text=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).text.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).text.set,'set');
globalMy.value.HTMLAnchorElement_text='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'coords','',true,undefined,undefined,function coords(){debugger;return globalMy.value.HTMLAnchorElement_coords;},function coords(val){debugger;globalMy.value.HTMLAnchorElement_coords=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).coords.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).coords.set,'set');
globalMy.value.HTMLAnchorElement_coords='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'charset','',true,undefined,undefined,function charset(){debugger;return globalMy.value.HTMLAnchorElement_charset;},function charset(val){debugger;globalMy.value.HTMLAnchorElement_charset=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).charset.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).charset.set,'set');
globalMy.value.HTMLAnchorElement_charset='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'name','',true,undefined,undefined,function name(){debugger;return globalMy.value.HTMLAnchorElement_name;},function name(val){debugger;globalMy.value.HTMLAnchorElement_name=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).name.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).name.set,'set');
globalMy.value.HTMLAnchorElement_name='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'rev','',true,undefined,undefined,function rev(){debugger;return globalMy.value.HTMLAnchorElement_rev;},function rev(val){debugger;globalMy.value.HTMLAnchorElement_rev=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).rev.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).rev.set,'set');
globalMy.value.HTMLAnchorElement_rev='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'shape','',true,undefined,undefined,function shape(){debugger;return globalMy.value.HTMLAnchorElement_shape;},function shape(val){debugger;globalMy.value.HTMLAnchorElement_shape=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).shape.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).shape.set,'set');
globalMy.value.HTMLAnchorElement_shape='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'origin','',true,undefined,undefined,function origin(){debugger;return globalMy.value.HTMLAnchorElement_origin;},undefined);globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).origin.get,'get');
globalMy.value.HTMLAnchorElement_origin='http://qikan.cqvip.com';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'protocol',':',true,undefined,undefined,function protocol(){debugger;return globalMy.value.HTMLAnchorElement_protocol;},function protocol(val){debugger;globalMy.value.HTMLAnchorElement_protocol=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).protocol.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).protocol.set,'set');
globalMy.value.HTMLAnchorElement_protocol='http:';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'username','',true,undefined,undefined,function username(){debugger;return globalMy.value.HTMLAnchorElement_username;},function username(val){debugger;globalMy.value.HTMLAnchorElement_username=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).username.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).username.set,'set');
globalMy.value.HTMLAnchorElement_username='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'password','',true,undefined,undefined,function password(){debugger;return globalMy.value.HTMLAnchorElement_password;},function password(val){debugger;globalMy.value.HTMLAnchorElement_password=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).password.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).password.set,'set');
globalMy.value.HTMLAnchorElement_password='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'host','',true,undefined,undefined,function host(){debugger;return globalMy.value.HTMLAnchorElement_host;},function host(val){debugger;globalMy.value.HTMLAnchorElement_host=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).host.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).host.set,'set');
globalMy.value.HTMLAnchorElement_host='qikan.cqvip.com';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'hostname','',true,undefined,undefined,function hostname(){debugger;return globalMy.value.HTMLAnchorElement_hostname;},function hostname(val){debugger;globalMy.value.HTMLAnchorElement_hostname=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hostname.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hostname.set,'set');
globalMy.value.HTMLAnchorElement_hostname='qikan.cqvip.com';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'port','',true,undefined,undefined,function port(){debugger;return globalMy.value.HTMLAnchorElement_port;},function port(val){debugger;globalMy.value.HTMLAnchorElement_port=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).port.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).port.set,'set');
globalMy.value.HTMLAnchorElement_port='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'pathname','',true,undefined,undefined,function pathname(){debugger;return globalMy.value.HTMLAnchorElement_pathname;},function pathname(val){debugger;globalMy.value.HTMLAnchorElement_pathname=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).pathname.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).pathname.set,'set');
globalMy.value.HTMLAnchorElement_pathname='/Search/SearchList';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'search','',true,undefined,undefined,function search(){debugger;return globalMy.value.HTMLAnchorElement_search;},function search(val){debugger;globalMy.value.HTMLAnchorElement_search=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).search.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).search.set,'set');
globalMy.value.HTMLAnchorElement_search='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'hash','',true,undefined,undefined,function hash(){debugger;return globalMy.value.HTMLAnchorElement_hash;},function hash(val){debugger;globalMy.value.HTMLAnchorElement_hash=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hash.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hash.set,'set');
globalMy.value.HTMLAnchorElement_hash='';
globalMy.mydefineProperty(HTMLAnchorElement.prototype,'href','',true,undefined,undefined,function href(){debugger;return globalMy.value.HTMLAnchorElement_href;},function href(val){debugger;globalMy.value.HTMLAnchorElement_href=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).href.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).href.set,'set');
globalMy.value.HTMLAnchorElement_href='http://qikan.cqvip.com/Search/SearchList';

globalMy.mydefineProperty(HTMLAnchorElement.prototype,'hrefTranslate','',true,undefined,undefined,function hrefTranslate(){debugger;return globalMy.value.HTMLAnchorElement_hrefTranslate;},function hrefTranslate(val){debugger;globalMy.value.HTMLAnchorElement_hrefTranslate=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hrefTranslate.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLAnchorElement.prototype).hrefTranslate.set,'set');
globalMy.value.HTMLAnchorElement_hrefTranslate='';
