HTMLBodyElement = function HTMLBodyElement() {
    globalMy.error("Illegal constructor" , `"TypeError: Illegal constructor
    at snippet:///%E8%84%9A%E6%9C%AC%E4%BB%A3%E7%A0%81%E6%AE%B5%20%2332:2:6"`)
}

globalMy.functionprotect(HTMLBodyElement);
globalMy.rename(HTMLBodyElement.prototype,"HTMLBodyElement")
Object.setPrototypeOf(HTMLBodyElement.prototype,HTMLElement.prototype)

globalMy.mydefineProperty(HTMLBodyElement.prototype,'text','',true,undefined,undefined,function text(){debugger;return globalMy.value.HTMLBodyElement_text;},function text(val){debugger;globalMy.value.HTMLBodyElement_text=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).text.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).text.set,'set');
globalMy.value.HTMLBodyElement_text='';
globalMy.mydefineProperty(HTMLBodyElement.prototype,'link','',true,undefined,undefined,function link(){debugger;return globalMy.value.HTMLBodyElement_link;},function link(val){debugger;globalMy.value.HTMLBodyElement_link=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).link.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).link.set,'set');
globalMy.value.HTMLBodyElement_link='';
globalMy.mydefineProperty(HTMLBodyElement.prototype,'vLink','',true,undefined,undefined,function vLink(){debugger;return globalMy.value.HTMLBodyElement_vLink;},function vLink(val){debugger;globalMy.value.HTMLBodyElement_vLink=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).vLink.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).vLink.set,'set');
globalMy.value.HTMLBodyElement_vLink='';
globalMy.mydefineProperty(HTMLBodyElement.prototype,'aLink','',true,undefined,undefined,function aLink(){debugger;return globalMy.value.HTMLBodyElement_aLink;},function aLink(val){debugger;globalMy.value.HTMLBodyElement_aLink=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).aLink.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).aLink.set,'set');
globalMy.value.HTMLBodyElement_aLink='';
globalMy.mydefineProperty(HTMLBodyElement.prototype,'bgColor','',true,undefined,undefined,function bgColor(){debugger;return globalMy.value.HTMLBodyElement_bgColor;},function bgColor(val){debugger;globalMy.value.HTMLBodyElement_bgColor=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).bgColor.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).bgColor.set,'set');
globalMy.value.HTMLBodyElement_bgColor='';
globalMy.mydefineProperty(HTMLBodyElement.prototype,'background','',true,undefined,undefined,function background(){debugger;return globalMy.value.HTMLBodyElement_background;},function background(val){debugger;globalMy.value.HTMLBodyElement_background=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).background.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).background.set,'set');
globalMy.value.HTMLBodyElement_background='';
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onblur',{},true,undefined,undefined,function onblur(){debugger;return globalMy.value.HTMLBodyElement_onblur;},function onblur(val){debugger;globalMy.value.HTMLBodyElement_onblur=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onblur.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onblur.set,'set');
globalMy.value.HTMLBodyElement_onblur={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onerror',{},true,undefined,undefined,function onerror(){debugger;return globalMy.value.HTMLBodyElement_onerror;},function onerror(val){debugger;globalMy.value.HTMLBodyElement_onerror=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onerror.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onerror.set,'set');
globalMy.value.HTMLBodyElement_onerror={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onfocus',{},true,undefined,undefined,function onfocus(){debugger;return globalMy.value.HTMLBodyElement_onfocus;},function onfocus(val){debugger;globalMy.value.HTMLBodyElement_onfocus=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onfocus.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onfocus.set,'set');
globalMy.value.HTMLBodyElement_onfocus={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onload',{},true,undefined,undefined,function onload(){debugger;return globalMy.value.HTMLBodyElement_onload;},function onload(val){debugger;globalMy.value.HTMLBodyElement_onload=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onload.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onload.set,'set');
globalMy.value.HTMLBodyElement_onload={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onresize',{},true,undefined,undefined,function onresize(){debugger;return globalMy.value.HTMLBodyElement_onresize;},function onresize(val){debugger;globalMy.value.HTMLBodyElement_onresize=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onresize.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onresize.set,'set');
globalMy.value.HTMLBodyElement_onresize={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onscroll',{},true,undefined,undefined,function onscroll(){debugger;return globalMy.value.HTMLBodyElement_onscroll;},function onscroll(val){debugger;globalMy.value.HTMLBodyElement_onscroll=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onscroll.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onscroll.set,'set');
globalMy.value.HTMLBodyElement_onscroll={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onafterprint',{},true,undefined,undefined,function onafterprint(){debugger;return globalMy.value.HTMLBodyElement_onafterprint;},function onafterprint(val){debugger;globalMy.value.HTMLBodyElement_onafterprint=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onafterprint.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onafterprint.set,'set');
globalMy.value.HTMLBodyElement_onafterprint={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onbeforeprint',{},true,undefined,undefined,function onbeforeprint(){debugger;return globalMy.value.HTMLBodyElement_onbeforeprint;},function onbeforeprint(val){debugger;globalMy.value.HTMLBodyElement_onbeforeprint=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onbeforeprint.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onbeforeprint.set,'set');
globalMy.value.HTMLBodyElement_onbeforeprint={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onbeforeunload',{},true,undefined,undefined,function onbeforeunload(){debugger;return globalMy.value.HTMLBodyElement_onbeforeunload;},function onbeforeunload(val){debugger;globalMy.value.HTMLBodyElement_onbeforeunload=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onbeforeunload.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onbeforeunload.set,'set');
globalMy.value.HTMLBodyElement_onbeforeunload={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onhashchange',{},true,undefined,undefined,function onhashchange(){debugger;return globalMy.value.HTMLBodyElement_onhashchange;},function onhashchange(val){debugger;globalMy.value.HTMLBodyElement_onhashchange=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onhashchange.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onhashchange.set,'set');
globalMy.value.HTMLBodyElement_onhashchange={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onlanguagechange',{},true,undefined,undefined,function onlanguagechange(){debugger;return globalMy.value.HTMLBodyElement_onlanguagechange;},function onlanguagechange(val){debugger;globalMy.value.HTMLBodyElement_onlanguagechange=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onlanguagechange.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onlanguagechange.set,'set');
globalMy.value.HTMLBodyElement_onlanguagechange={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onmessage',{},true,undefined,undefined,function onmessage(){debugger;return globalMy.value.HTMLBodyElement_onmessage;},function onmessage(val){debugger;globalMy.value.HTMLBodyElement_onmessage=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onmessage.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onmessage.set,'set');
globalMy.value.HTMLBodyElement_onmessage={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onmessageerror',{},true,undefined,undefined,function onmessageerror(){debugger;return globalMy.value.HTMLBodyElement_onmessageerror;},function onmessageerror(val){debugger;globalMy.value.HTMLBodyElement_onmessageerror=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onmessageerror.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onmessageerror.set,'set');
globalMy.value.HTMLBodyElement_onmessageerror={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onoffline',{},true,undefined,undefined,function onoffline(){debugger;return globalMy.value.HTMLBodyElement_onoffline;},function onoffline(val){debugger;globalMy.value.HTMLBodyElement_onoffline=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onoffline.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onoffline.set,'set');
globalMy.value.HTMLBodyElement_onoffline={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'ononline',{},true,undefined,undefined,function ononline(){debugger;return globalMy.value.HTMLBodyElement_ononline;},function ononline(val){debugger;globalMy.value.HTMLBodyElement_ononline=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).ononline.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).ononline.set,'set');
globalMy.value.HTMLBodyElement_ononline={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onpagehide',{},true,undefined,undefined,function onpagehide(){debugger;return globalMy.value.HTMLBodyElement_onpagehide;},function onpagehide(val){debugger;globalMy.value.HTMLBodyElement_onpagehide=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onpagehide.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onpagehide.set,'set');
globalMy.value.HTMLBodyElement_onpagehide={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onpageshow',{},true,undefined,undefined,function onpageshow(){debugger;return globalMy.value.HTMLBodyElement_onpageshow;},function onpageshow(val){debugger;globalMy.value.HTMLBodyElement_onpageshow=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onpageshow.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onpageshow.set,'set');
globalMy.value.HTMLBodyElement_onpageshow={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onpopstate',{},true,undefined,undefined,function onpopstate(){debugger;return globalMy.value.HTMLBodyElement_onpopstate;},function onpopstate(val){debugger;globalMy.value.HTMLBodyElement_onpopstate=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onpopstate.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onpopstate.set,'set');
globalMy.value.HTMLBodyElement_onpopstate={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onrejectionhandled',{},true,undefined,undefined,function onrejectionhandled(){debugger;return globalMy.value.HTMLBodyElement_onrejectionhandled;},function onrejectionhandled(val){debugger;globalMy.value.HTMLBodyElement_onrejectionhandled=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onrejectionhandled.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onrejectionhandled.set,'set');
globalMy.value.HTMLBodyElement_onrejectionhandled={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onstorage',{},true,undefined,undefined,function onstorage(){debugger;return globalMy.value.HTMLBodyElement_onstorage;},function onstorage(val){debugger;globalMy.value.HTMLBodyElement_onstorage=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onstorage.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onstorage.set,'set');
globalMy.value.HTMLBodyElement_onstorage={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onunhandledrejection',{},true,undefined,undefined,function onunhandledrejection(){debugger;return globalMy.value.HTMLBodyElement_onunhandledrejection;},function onunhandledrejection(val){debugger;globalMy.value.HTMLBodyElement_onunhandledrejection=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onunhandledrejection.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onunhandledrejection.set,'set');
globalMy.value.HTMLBodyElement_onunhandledrejection={};
globalMy.mydefineProperty(HTMLBodyElement.prototype,'onunload',{},true,undefined,undefined,function onunload(){debugger;return globalMy.value.HTMLBodyElement_onunload;},function onunload(val){debugger;globalMy.value.HTMLBodyElement_onunload=val;});globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onunload.get,'get');globalMy.functionprotect(Object.getOwnPropertyDescriptors(HTMLBodyElement.prototype).onunload.set,'set');
globalMy.value.HTMLBodyElement_onunload={};


